# Generated by Django 4.2.3 on 2023-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
    ]
