# Generated by Django 4.2.3 on 2023-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='owner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
