# Generated by Django 4.2.3 on 2023-08-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='address',
        ),
        migrations.RemoveField(
            model_name='car',
            name='phone',
        ),
    ]
